sudo: false
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37,mypy,flake8
    - os: osx
      language: generic
      env: PYTHON='3.5.6' TOXENV=py35
    - os: osx
      language: generic
      env: PYTHON='3.6.7' TOXENV=py36
    - os: osx
      language: generic
      env: PYTHON='3.7.1' TOXENV=py37

cache:
  pip: true
  directories:
    - $HOME/.pyenv

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        source travis_install_pyenv.sh
        python --version
    fi

  - pip install poetry tox
script: tox
