language: python
python:
  - '3.5'
  - '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry tox-travis
script: tox
notifications:
  on_success: change
  on_failure: always
